// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(FeWoDbContext))]
    [Migration("20250610095939_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Buchung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("AnzahlPersonen")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long>("FeWoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Inaktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("KalenderWoche")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FeWoId", "KalenderWoche")
                        .IsUnique();

                    b.ToTable("Buchung");
                });

            modelBuilder.Entity("API.Models.FeWo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Inaktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreisProWoche")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeWo");
                });

            modelBuilder.Entity("API.Models.Buchung", b =>
                {
                    b.HasOne("API.Models.FeWo", "FeWo")
                        .WithMany("Buchungen")
                        .HasForeignKey("FeWoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeWo");
                });

            modelBuilder.Entity("API.Models.FeWo", b =>
                {
                    b.Navigation("Buchungen");
                });
#pragma warning restore 612, 618
        }
    }
}
